version: "3.9"

name: "toggl-test-signer"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file: .env
    environment: # Overwrite some ENVs for Docker environment.
      - HOST=0.0.0.0
    volumes:
      - .:/project
    ports:
      - "${PORT}:${PORT}"
