version: "3.9"

name: "toggl-test-signer"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file: .env
    environment: # Overwrite some ENVs for Docker environment.
      - HOST=0.0.0.0
      - MYSQL_DSN=root:root@tcp(db:3306)/toggl_test_signer
    volumes:
      - .:/project
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    env_file: .env
    ports:
      - "${DATABASE_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
